[font]
size = 12.5

[font.normal]
family = 'Agave Nerd Font'
style = 'Regular'

[font.bold]
family = 'Agave Nerd Font'
style = 'Regular'

[font.italic]
family = 'Agave Nerd Font'
style = 'Italic'

[font.bold_italic]
family = 'Agave Nerd Font'
style = 'Italic'

[font.offset]
x = 2
y = 8

[font.glyph_offset]
x = 1
y = 2
