[font]
size = 11.5

[font.normal]
family = "Cascadia Code NF"
style = "ExtraLight"

[font.bold]
family = "Cascadia Code NF"
style = "ExtraLight"

[font.italic]
family = "Cascadia Code NF"
style = "ExtraLight"

[font.bold_italic]
family = "Cascadia Code NF"
style = "ExtraLight"

[font.offset]
x = 1
y = 1

[font.glyph_offset]
x = 0
y = 0
