[font]
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight Italic"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight Italic"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
