[font]
size = 11

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Light"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Light"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Light"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Light"

[font.offset]
x = 1
y = 2

[font.glyph_offset]
x = 0
y = 0
