[font]
size = 10.5

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 10

[font.glyph_offset]
x = 0
y = 5
