[font]
size = 11

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2
