[font]
size = 9.5

[font.normal]
family = 'Monoid Nerd Font'
style = 'Retina'

[font.bold]
family = 'Monoid Nerd Font'
style = 'Retina'

[font.italic]
family = 'Monoid Nerd Font'
style = 'Retina'

[font.bold_italic]
family = 'Monoid Nerd Font'
style = 'Retina'

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 1
