[font]
size = 11

[font.normal]
family = 'Martian Mono'
style = 'Light'

[font.bold]
family = 'Martian Mono'
style = 'Light'

[font.italic]
family = 'Martian Mono'
style = 'Light'

[font.bold_italic]
family = 'Martian Mono'
style = 'Light'

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 3
