[font]
size = 12.5

[font.normal]
family = 'NovaMono'
style = 'Regular'

[font.bold]
family = 'NovaMono'
style = 'Regular'

[font.italic]
family = 'NovaMono'
style = 'Regular'

[font.bold_italic]
family = 'NovaMono'
style = 'Regular'

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 3
