[font]
size = 13.5

[font.normal]
family = 'InconsolataGo Nerd Font'
style = 'Regular'

[font.bold]
family = 'InconsolataGo Nerd Font'
style = 'Regular'

[font.italic]
family = 'InconsolataGo Nerd Font'
style = 'Regular'

[font.bold_italic]
family = 'InconsolataGo Nerd Font'
style = 'Regular'

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0
