[font]
size = 11

[font.normal]
family = 'Iosevka SS01'
style = 'Extended'

[font.bold]
family = 'Iosevka SS01'
style = 'Extended'

[font.italic]
family = 'Iosevka SS01'
style = 'Extended'

[font.bold_italic]
family = 'Iosevka SS01'
style = 'Extended'

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
