[font]
size = 14

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
