[font]
size = 11

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 4

[font.glyph_offset]
x = 1
y = 2
