[font]
size = 10.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2

