[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.offset]
x = 0
y = 5

[font.glyph_offset]
x = 0
y = 3

