[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[font.bold]
family = "FiraCode Nerd Font"
style = "Light"

[font.italic]
family = "FiraCode Nerd Font"
style = "Light"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

