[font]
size = 11.5

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0
