[font]
size = 11

[font.normal]
family = 'Hurmit Nerd Font'
style = 'Regular'

[font.bold]
family = 'Hurmit Nerd Font'
style = 'Regular'

[font.italic]
family = 'Hurmit Nerd Font'
style = 'Regular'

[font.bold_italic]
family = 'Hurmit Nerd Font'
style = 'Regular'

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
