[font]
size = 12

[font.normal]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.bold]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.italic]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.bold_italic]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.offset]
x = 0
y = -2

[font.glyph_offset]
x = 0
y = -1
