[font]
size = 10

[font.normal]
family = 'BlexMono Nerd Font'
style = 'Medium'

[font.bold]
family = 'BlexMono Nerd Font'
style = 'Medium'

[font.italic]
family = 'BlexMono Nerd Font'
style = 'Medium'

[font.bold_italic]
family = 'BlexMono Nerd Font'
style = 'Medium'

[font.offset]
x = 0
y = 8

[font.glyph_offset]
x = 0
y = 4
