[font]
size = 12

[font.normal]
family = 'BlexMono Nerd Font'
style = 'Regular'

[font.bold]
family = 'BlexMono Nerd Font'
style = 'Regular'

[font.italic]
family = 'BlexMono Nerd Font'
style = 'Italic'

[font.bold_italic]
family = 'BlexMono Nerd Font'
style = 'Italic'

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 2
