[font]
size = 10.5

[font.normal]
family = 'BlexMono Nerd Font'
style = 'Medium Italic'

[font.bold]
family = 'BlexMono Nerd Font'
style = 'Medium Italic'

[font.italic]
family = 'BlexMono Nerd Font'
style = 'Medium Italic'

[font.bold_italic]
family = 'BlexMono Nerd Font'
style = 'Medium Italic'

[font.offset]
x = 1
y = 7

[font.glyph_offset]
x = 0
y = 4
