[font]
size = 11.5

[font.normal]
family = 'InputMono Nerd Font Mono'
style = 'Condensed'

[font.bold]
family = 'InputMono Nerd Font Mono'
style = 'Condensed'

[font.italic]
family = 'InputMono Nerd Font Mono'
style = 'Condensed'

[font.bold_italic]
family = 'InputMono Nerd Font Mono'
style = 'Condensed'

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
