[font]
size = 12

[font.normal]
family = 'InputMono Nerd Font'
style = 'Narrow'

[font.bold]
family = 'InputMonoNarrow Nerd Font'
style = 'Narrow'
# style = 'Medium'

[font.italic]
family = 'InputMonoNarrow Nerd Font'
style = 'Narrow'

[font.bold_italic]
family = 'InputMonoNarrow Nerd Font'
style = 'Narrow'
# style = 'Medium'

# [font.bold_italic]
# family = 'InputMonoNarrowIta Nerd Font'
# style = 'Medium'

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
