[font]
size = 12

[font.normal]
family = 'InputMono Nerd Font'
style = 'Narrow'

[font.bold]
family = 'InputMono Nerd Font'
style = 'Narrow'

[font.italic]
family = 'InputMonoNarrow Nerd Font'
style = 'Italic'

[font.bold_italic]
family = 'InputMonoNarrow Nerd Font'
style = 'Italic'

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
