[font]
size = 12.4

[font.normal]
family = 'InputMonoCondensed Nerd Font Mono'
style = 'Light'

[font.bold]
family = 'InputMonoCondensed Nerd Font Mono'
style = 'Light'

[font.italic]
family = 'InputMonoCondensed Nerd Font Mono'
style = 'Light'

[font.bold_italic]
family = 'InputMonoCondensed Nerd Font Mono'
style = 'Light'

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
