[font]
size = 12

[font.normal]
family = 'IntoneMono Nerd Font'
style = 'Regular'

[font.bold]
family = 'IntoneMono Nerd Font'
style = 'Regular'

[font.italic]
family = 'IntoneMono Nerd Font'
style = 'Regular'

[font.bold_italic]
family = 'IntoneMono Nerd Font'
style = 'Regular'

[font.offset]
x = 0
y = -4

[font.glyph_offset]
x = 0
y = 0
