[font]
size = 12.5

[font.normal]
family = 'IntoneMono Nerd Font'
style = 'Medium'

[font.bold]
family = 'IntoneMono Nerd Font'
style = 'Medium'

[font.italic]
family = 'IntoneMono Nerd Font'
style = 'Medium'

[font.bold_italic]
family = 'IntoneMono Nerd Font'
style = 'Medium'

[font.offset]
x = -1
y = -2

[font.glyph_offset]
x = 0
y = 0
