[font]
size = 10.5

[font.normal]
family = 'IosevkaCustom Nerd Font Mono'
style = 'Light'

[font.bold]
family = 'IosevkaCustom Nerd Font Mono'
style = 'Light'

[font.italic]
family = 'IosevkaCustom Nerd Font Mono'
style = 'Light'

[font.bold_italic]
family = 'IosevkaCustom Nerd Font Mono'
style = 'Light'

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
