[font]
size = 12

[font.normal]
family = 'Iosevka Custom'
style = 'Regular'

[font.bold]
family = 'Iosevka Custom'
style = 'Regular'

[font.italic]
family = 'Iosevka Custom'
style = 'Regular'

[font.bold_italic]
family = 'Iosevka Custom'
style = 'Regular'

[font.offset]
x = 1
y = -2

[font.glyph_offset]
x = 0
y = 0
