[font]
size = 12.5

[font.normal]
family = 'Iosevka Custom'
style = 'Medium'

[font.bold]
family = 'Iosevka Custom'
style = 'Medium'

[font.italic]
family = 'Iosevka Custom'
style = 'Medium'

[font.bold_italic]
family = 'Iosevka Custom'
style = 'Medium'

[font.offset]
x = 1
y = 6

[font.glyph_offset]
x = 0
y = 4
