[font]
size = 12.5

[font.normal]
family = 'Iosevka Nerd Font'
style = 'Medium'

[font.bold]
family = 'Iosevka Nerd Font'
style = 'Medium'

[font.italic]
family = 'Iosevka Nerd Font'
style = 'Medium'

[font.bold_italic]
family = 'Iosevka Nerd Font'
style = 'Medium'

[font.offset]
x = 1
y = 3

[font.glyph_offset]
x = 1
y = 1
