[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 4

[font.glyph_offset]
x = 0
y = 2

