[font]
size = 11.9

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.offset]
x = 1
y = -1

[font.glyph_offset]
x = 0
y = 0

