[font]
size = 11.2

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight Italic"

[font.offset]
x = 1
y = 2

[font.glyph_offset]
x = 0
y = 1

