[font]
size = 11

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[font.bold]
family = "Maple Mono NF"
style = "Regular"

[font.italic]
family = "Maple Mono NF"
style = "Regular"

[font.bold_italic]
family = "Maple Mono NF"
style = "Regular"

[font.offset]
x = 1
y = 1

[font.glyph_offset]
x = 0
y = 0
