[font]
size = 10.5

[font.normal]
family = "Maple Mono NF"
style = "Italic"

[font.bold]
family = "Maple Mono NF"
style = "Italic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.bold_italic]
family = "Maple Mono NF"
style = "Italic"

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0
