[font]
size = 10

[font.normal]
family = "Maple Mono NF"
style = "Medium"

[font.bold]
family = "Maple Mono NF"
style = "Medium"

[font.italic]
family = "Maple Mono NF"
style = "Medium Italic"

[font.bold_italic]
family = "Maple Mono NF"
style = "Medium Italic"

[font.offset]
x = 1
y = 7

[font.glyph_offset]
x = 0
y = 3
