[font]
size = 12

[font.normal]
family = "Maple Mono NF"
style = "ExtraLight"

[font.bold]
family = "Maple Mono NF"
style = "ExtraLight"

[font.italic]
family = "Maple Mono NF"
style = "ExtraLight"

[font.bold_italic]
family = "Maple Mono NF"
style = "ExtraLight"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
