[font]
size = 10.5

[font.normal]
family = "MonaspaceRadon Nerd Font"
style = "Regular"

[font.bold]
family = "MonaspaceRadon Nerd Font"
style = "Regular"

[font.italic]
family = "MonaspaceRadon Nerd Font"
style = "Regular"

[font.bold_italic]
family = "MonaspaceRadon Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 8

[font.glyph_offset]
x = 0
y = 3
