[font]
size = 10.5

[font.normal]
family = "MonaspiceRn Nerd Font"
style = "Light"

[font.bold]
family = "MonaspiceRn Nerd Font"
style = "Light"

[font.italic]
family = "MonaspiceRn Nerd Font"
style = "Light"

[font.bold_italic]
family = "MonaspiceRn Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 0
