[font]
size = 10.5

[font.normal]
family = "MonaspaceRadon Nerd Font"
style = "ExtraLight"

[font.bold]
family = "MonaspaceRadon Nerd Font"
style = "ExtraLight"

[font.italic]
family = "MonaspaceRadon Nerd Font"
style = "ExtraLight"

[font.bold_italic]
family = "MonaspaceRadon Nerd Font"
style = "ExtraLight"

[font.offset]
x = 1
y = 3

[font.glyph_offset]
x = 0
y = 1
