[font]
size = 13

[font.normal]
family = "MonaspaceKrypton Nerd Font"
style = "Regular"

[font.bold]
family = "MonaspaceKrypton Nerd Font"
style = "Regular"

[font.italic]
family = "MonaspaceKrypton Nerd Font"
style = "Regular"

[font.bold_italic]
family = "MonaspaceKrypton Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
