[font]
size = 11

[font.normal]
family = 'Mononoki Nerd Font'
style = 'Bold'

[font.bold]
family = 'Mononoki Nerd Font'
style = 'Bold'

[font.italic]
family = 'Mononoki Nerd Font'
style = 'Bold Italic'

[font.bold_italic]
family = 'Mononoki Nerd Font'
style = 'Bold Italic'

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 1
