[font]
size = 14

[font.normal]
family = 'Ligamononoki Nerd Font'
style = 'Regular'

[font.bold]
family = 'Ligamononoki Nerd Font'
style = 'Regular'

[font.italic]
family = 'Ligamononoki Nerd Font'
style = 'Regular'

[font.bold_italic]
family = 'Ligamononoki Nerd Font'
style = 'Regular'

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
