[font]
size = 12.5

[font.normal]
family = 'Mononoki Nerd Font Mono'
style = 'Regular'

[font.bold]
family = 'Mononoki Nerd Font Mono'
style = 'Regular'

[font.italic]
family = 'Mononoki Nerd Font Mono'
style = 'Italic'

[font.bold_italic]
family = 'Mononoki Nerd Font Mono'
style = 'Italic'

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
