[font]
size = 13

[font.normal]
family = 'Mononoki Nerd Font'
style = 'Regular'

[font.bold]
family = 'Mononoki Nerd Font'
style = 'Regular'

[font.italic]
family = 'Mononoki Nerd Font'
style = 'Italic'

[font.bold_italic]
family = 'Mononoki Nerd Font'
style = 'Italic'

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
