[font]
size = 10.5

[font.normal]
family = 'Rec Mono Custom'
style = 'Regular'

[font.bold]
family = 'Rec Mono Custom'
style = 'Regular'

[font.italic]
family = 'Rec Mono Custom'
style = 'Regular'

[font.bold_italic]
family = 'Rec Mono Custom'
style = 'Regular'

[font.offset]
x = 1
y = 6

[font.glyph_offset]
x = 0
y = 3
