[font]
size = 11.5

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 0
