[font]
size = 10.5

[font.normal]
family = "Serious Sans Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Serious Sans Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Serious Sans Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "Serious Sans Nerd Font Mono"
style = "Regular"

[font.offset]
x = 2
y = 9

[font.glyph_offset]
x = 1
y = 2
