[font]
size = 13

[font.normal]
family = "SeriousShanns Nerd Font"
style = "Light"

[font.bold]
family = "SeriousShanns Nerd Font"
style = "Light"

[font.italic]
family = "SeriousShanns Nerd Font"
style = "Light"

[font.bold_italic]
family = "SeriousShanns Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 0
