[font]
size = 11

[font.normal]
family = "SeriousShanns Nerd Font"
style = "Light"

[font.bold]
family = "SeriousShanns Nerd Font"
style = "Light"

[font.italic]
family = "SeriousShanns Nerd Font"
style = "Light Italic"

[font.bold_italic]
family = "SeriousShanns Nerd Font"
style = "Light Italic"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 1
