[font]
size = 10.5

[font.normal]
family = "SeriousSans Nerd Font Mono"
style = "Light"

[font.bold]
family = "SeriousSans Nerd Font Mono"
style = "Light"

[font.italic]
family = "SeriousSans Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "SeriousSans Nerd Font Mono"
style = "Light"

[font.offset]
x = 2
y = 8

[font.glyph_offset]
x = 1
y = 2
