[font]
size = 10

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font"
style = "Regular"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 3
