[font]
size = 12

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[font.bold]
family = "SFMono Nerd Font"
style = "Medium"

[font.italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
