[font]
size = 13

[font.normal]
family = 'ShureTechMono Nerd Font Mono'
style = 'Regular'

[font.bold]
family = 'ShureTechMono Nerd Font Mono'
style = 'Regular'

[font.italic]
family = 'ShureTechMono Nerd Font Mono'
style = 'Italic'

[font.bold_italic]
family = 'ShureTechMono Nerd Font Mono'
style = 'Italic'

[font.offset]
x = -1
y = 1

[font.glyph_offset]
x = 0
y = 1
