[font]
size = 13.5

[font.normal]
family = 'UbuntuMono Nerd Font Mono'
style = 'Regular'

[font.bold]
family = 'UbuntuMono Nerd Font Mono'
style = 'Regular'

[font.italic]
family = 'UbuntuMono Nerd Font Mono'
style = 'Regular'

[font.bold_italic]
family = 'UbuntuMono Nerd Font Mono'
style = 'Regular'

[font.offset]
x = 1
y = 4

[font.glyph_offset]
x = 0
y = 2

