[font]
size = 10.5

[font.normal]
family = 'VictorMono Nerd Font'
style = 'Bold'

[font.bold]
family = 'VictorMono Nerd Font'
style = 'Bold'

[font.italic]
family = 'VictorMono Nerd Font'
style = 'Bold'

[font.bold_italic]
family = 'VictorMono Nerd Font'
style = 'Bold'

[font.offset]
x = 2
y = 6

[font.glyph_offset]
x = 1
y = 4
