[font]
size = 11

[font.normal]
family = 'VictorMono Nerd Font'
style = 'Medium'

[font.bold]
family = 'VictorMono Nerd Font'
style = 'Medium'

[font.italic]
family = 'VictorMono Nerd Font'
style = 'Medium Italic'

[font.bold_italic]
family = 'VictorMono Nerd Font'
style = 'Medium Italic'

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0
