[font]
size = 10.5

[font.normal]
family = 'VictorMono Nerd Font'
style = 'SemiBold'

[font.bold]
family = 'VictorMono Nerd Font'
style = 'SemiBold'

[font.italic]
family = 'VictorMono Nerd Font'
style = 'SemiBold'

[font.bold_italic]
family = 'VictorMono Nerd Font'
style = 'SemiBold'

[font.offset]
x = 1
y = 2

[font.glyph_offset]
x = 0
y = 1
