[font]
size = 11.5

[font.normal]
family = 'VictorMono Nerd Font'
style = 'SemiBold'

[font.bold]
family = 'VictorMono Nerd Font'
style = 'Bold'

[font.italic]
family = 'VictorMono Nerd Font'
style = 'SemiBold'

[font.bold_italic]
family = 'VictorMono Nerd Font'
style = 'Bold'

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = 0
