[font]
size = 11.5

[font.normal]
family = 'ZedMono Nerd Font'
style = 'Extended'

[font.bold]
family = 'ZedMono Nerd Font'
style = 'Extended'

[font.italic]
family = 'ZedMono Nerd Font'
style = 'Extended'

[font.bold_italic]
family = 'ZedMono Nerd Font'
style = 'Extended'

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 0
