[font]
size = 11

[font.normal]
family = 'ZedMono Nerd Font Mono'
style = 'Light'

[font.bold]
family = 'ZedMono Nerd Font Mono'
style = 'Light'

[font.italic]
family = 'ZedMono Nerd Font Mono'
style = 'Light'

[font.bold_italic]
family = 'ZedMono Nerd Font Mono'
style = 'Light'

[font.offset]
x = 2
y = 2

[font.glyph_offset]
x = 1
y = 1
