format="""
  $directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
$character
"""
# symbol=""

[git_branch]
format="[$branch]($style) "

[git_state]
format="($state( $progress_current/$progress_total)($style)) "

[git_status]
format="([$all_status$ahead_behind]($style) )"
